### ISSUE TITLE
npm install react-native-key-pair gives an error that react-native-key-pair is not in the npm registry

### ISSUE THREAD

**Issue by SanchiSinghal** [SamSaffron/react-native-key-pair#2]
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "react-native-key-pair"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/react-native-key-pair
npm ERR! 404 
npm ERR! 404  'react-native-key-pair' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/../../npm-debug.log

**Comment by naveedn** [comment]
Hey! I am also having this problem. Is there anything I can do to help get this problem resolved?

**Comment by amitaymolko** [comment]
you can add 
`    
"react-native-key-pair": "git://github.com/SamSaffron/react-native-key-pair.git",
`
to `package.json` `dependencies` to use the package without npm

**Comment by naveedn** [comment]
Ahh. I was trying to do it behind a corporate proxy -- would not let me install via github. I ended up being able to manually add it as a dependency -- not ideal, but it allowed me to get past my problem.

Thanks for the response!

**Comment by SanchiSinghal** [comment]
Ya.. So this library is not being added in the npm so we need to add it manually .

**Comment by crafterm** [comment]
Hi guys, perhaps we should reopen this as a documentation bug, since the readme/front page indicates installing via npm as the main way to get up and running - @SamSaffron mate if its not going to be in npm I can submit a PR to remove those lines from the readme?

**Comment by amitaymolko** [comment]
I have written a native rsa library with additional encryption/decryption functionality, and it is on npm :)
It was originally based on this project.
Feel free to check it out: https://github.com/amitaymolko/react-native-rsa-native
PRs welcome

**Comment by crafterm** [comment]
@amitaymolko I saw your library and did take a closer look - very nice! Was actually wondering though why you preferred OpenSSL over the iOS inbuilt crypto?

**Comment by amitaymolko** [comment]
@crafterm I couldn't find a built in library in iOS can you send me a link to the docs?

**Comment by crafterm** [comment]
@amitaymolko sure mate i'll take the conversation over to your project

**Comment by SanchiSinghal** [comment]
So now, do I need to reopen the issue ?
